### ISSUE TITLE
Schema.org lookup returns empty results in version 0.8

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [kingsdigitallab/django-controlled-vocabulary#11]
Both the widget and vocab search return no terms for any look up in the schema.org vocabulary.

```
$ pm vocab search -f schema -p movie
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
[...]
Exception: download vocabularies/schema-types.csv failed
```

**Comment by geoffroy-noel-ddh** [comment]
Schema.org CSV has recently moved to a new URL. Updated schema.py
